### ISSUE TITLE
how to example with ns vue 

### ISSUE THREAD

**Issue by taothai** [GeoTecINIT/nativescript-task-dispatcher#12] opened 2020-11-30 06:00 UTC
hi how to work with nsvue 

thank for guild

**Comment by agonper** [comment] 2020-11-30 11:26
Hi @taothai,

First of all, thanks for showing your interest in our plugin.

This plugin does not contain any UI components so the steps to follow in NS Vue should be the same than for NS Core or NS Angular. Anyway I can check this for you.

Before helping you further, I would appreciate if you can answer the following questions:
- Are you aware of that this plugin does not have multi platform support? It is Android-only, for the moment.
- What kind of problem are you trying to solve with our plugin?

Thank you.

**Comment by taothai** [comment] 2020-12-19 02:11
@agonper  
First of all, thanks for reply 
how to  support ns7 

Thank you.

**Comment by agonper** [comment] 2020-12-19 15:43
Hello @taothai. Our migration plans to NS7 have been delayed because of problems with the test runner in that NativeScript version. We'll fully migrate to it once it becomes more stable.

Meanwhile, perhaps you can try to add the plugin to a NS7 app, but I'm not sure it will work. Sorry for the inconvenience.

**Comment by agonper** [comment] 2021-02-22 15:43
Duplicate of #18. Closing given the other one is more focused on the topic. For any NS 7 updates, please, refer to that issue. Thanks.

**Closed by agonper** 2021-02-22 15:43 UTC
Labels: enhancement, question
